apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-upload-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: file-upload-app
  template:
    metadata:
      labels:
        app: file-upload-app
    spec:
      containers:
      - name: file-upload-container
        image: aashimatyagi/file-upload:__TAG__
        ports:
        - containerPort: 5000
